# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

 
trigger:
- main

pool: 'Default'

steps:

- script: |
    dir
  displayName: 'Check current directory'

- script: |
    appscansrccli scr cli_script1.txt

- powershell: .\my-script.ps1
  
  displayName: 'Perform AppScan Source SAST Scan, Establish connection to powershell, Generate PDF report, publish to ASE'


- task: PublishPipelineArtifact@1
  inputs:
   targetPath: '$(Pipeline.Workspace)/s/report_FP.pdf'
   publishLocation: 'pipeline'

